version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - task_manager_network

  task_management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_management
    command: gunicorn --bind 0.0.0.0:8001 task_management.wsgi:application
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - task_manager_network

volumes:
  mongo_data:

networks:
  task_manager_network:
    driver: bridge
